### ISSUE TITLE
Bio::DB::Sam class fetch/view does not recognize chromosomes; samools executes correctly.

### ISSUE THREAD

**Issue by MatthewRalston** [helios/bioruby-samtools#47]
Hello again. I am walking through [your wiki](http://bioruby.open-bio.org/wiki/Bio-samtools#Getting_Alignments) and encountering some problems. After loading a file, I'm trying to interact with the alignment objects although the fetch and view methods don't recognize the chromosome that the reads are aligned to (see the header and sample read below). However, the samtools command below is executing correctly. How can I facilitate this?
bio-samtools v2.3.2

```rb
>bam=Bio::DB::Sam.new(:bam=>"test_files/test.bam",:fasta=>"test_files/NC_001988.ffn") && bam.open
>bam.fetch("NC_001988.2",0,200) {|x| puts "HELLO"}
Exception: [view] The sequence NC_001988.2 is not in the bam file
	from /Users/Matthew/.rvm/gems/ruby-2.1.2@lci/gems/bio-samtools-2.3.2/lib/bio/db/sam.rb:67:in `view'
	from /Users/Matthew/.rvm/gems/ruby-2.1.2@lci/gems/bio-samtools-2.3.2/lib/bio/db/sam.rb:96:in `fetch'
	from (irb):4
	from /Users/Matthew/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'

>puts `samtools view -h test_files/test.bam NC_001988.2:0-200 | head`
@HD	VN:1.0	SO:coordinate
@SQ	SN:NC_003030.1	LN:3940880
@SQ	SN:NC_001988.2	LN:192000
@PG	ID:bowtie2	PN:bowtie2	VN:2.1.0
HWI-ST741:439:H9G3UADXX:2:2103:18990:5489_2:N:0:ATCACG	153	NC_001988.2	7	0	8M2D68M	=	7	0	TTGATGGATATAGCATATTTAGGAGGTATTTAAAATGAAAGAATATAAATATACTGTTATTACAGGAGCAAGTACG	JIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIJJJJJJJJJJJHJJJJJJJJJJHHHHHFFFFFBCC	AS:i:-39	XN:i:0	XM:i:5	XO:i:1	XG:i:2	NM:i:7	MD:Z:0A1A3C1^AT65T1A0	YT:Z:UP
```

**Comment by homonecloco** [comment]
Hi again, 
Can you send us the output of:
'''
samtools idxstats test_files/test.bam
'''
Thanks, 
Ricardo.

**Comment by homonecloco** [comment]
Also, if you can make a toy example that reproduces the bug (1 read, and the fasta file with the region), I can have a better look at it, I can't fix it.

**Comment by MatthewRalston** [comment]
Thank you for your help @homonecloco . The test files can be found in the link below and work with the code from the examples above.
https://github.com/MatthewRalston/LCI/tree/master/test_files

```
>samtools idxstats test_files/test.bam
NC_003030.1	3940880	0	0
NC_001988.2	192000	35	1
*	0	0	0
```

**Comment by homonecloco** [comment]
Thanks for the example. I am trying to reproduce the bug, but I can't. 

```rb
2.1.0 :001 > require 'bio-samtools'
 => true
2.1.0 :002 > @testLCI                    = "test/samples/LCI/test.bam"
 => "test/samples/LCI/test.bam"
2.1.0 :003 > @testLCIref                 = "test/samples/LCI/NC_001988.ffn"
 => "test/samples/LCI/NC_001988.ffn"
2.1.0 :004 > bam=Bio::DB::Sam.new(:bam=>@testLCI,:fasta=>@testLCIref)
 => #<Bio::DB::Sam:0x000001011eb110 @fasta="test/samples/LCI/NC_001988.ffn", @bam="test/samples/LCI/test.bam", @samtools="/Users/ramirezr/.rvm/gems/ruby-2.1.0/gems/bio-samtools-2.3.2/lib/bio/db/sam/external/samtools", @bcftools="/Users/ramirezr/.rvm/gems/ruby-2.1.0/gems/bio-samtools-2.3.2/lib/bio/db/sam/external/bcftools", @last_command=nil>
2.1.0 :005 >  bam.open
 => true
2.1.0 :006 > count = 0
 => 0
2.1.0 :007 >     bam.fetch("NC_001988.2",0,200) do|x|
2.1.0 :008 >           count += 1
2.1.0 :009?>         puts "#{count}: #{x}"
2.1.0 :010?>
2.1.0 :011 >         end
/Users/ramirezr/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/open3.rb:193: warning: Insecure world writable dir /usr/local/cuda/bin in PATH, mode 040777
1: #<Bio::DB::Alignment:0x000001012132f0>
2: #<Bio::DB::Alignment:0x00000101212760>
3: #<Bio::DB::Alignment:0x00000101212260>
4: #<Bio::DB::Alignment:0x000001012115e0>
5: #<Bio::DB::Alignment:0x00000101210960>
6: #<Bio::DB::Alignment:0x00000103117c78>
7: #<Bio::DB::Alignment:0x00000103116ff8>
8: #<Bio::DB::Alignment:0x00000103116350>
9: #<Bio::DB::Alignment:0x000001031156d0>
10: #<Bio::DB::Alignment:0x00000103114a50>
11: #<Bio::DB::Alignment:0x0000010311fd60>
12: #<Bio::DB::Alignment:0x0000010311f0e0>
13: #<Bio::DB::Alignment:0x0000010311e460>
14: #<Bio::DB::Alignment:0x0000010311d7e0>
15: #<Bio::DB::Alignment:0x0000010311cb60>
16: #<Bio::DB::Alignment:0x00000103127e98>
17: #<Bio::DB::Alignment:0x00000103127308>
18: #<Bio::DB::Alignment:0x00000103126688>
19: #<Bio::DB::Alignment:0x00000103125a08>
20: #<Bio::DB::Alignment:0x00000103124d88>
21: #<Bio::DB::Alignment:0x00000103124108>
22: #<Bio::DB::Alignment:0x0000010312f440>
23: #<Bio::DB::Alignment:0x0000010312e8b0>
24: #<Bio::DB::Alignment:0x0000010312dc30>
25: #<Bio::DB::Alignment:0x0000010312d0a0>
26: #<Bio::DB::Alignment:0x0000010312c420>
27: #<Bio::DB::Alignment:0x00000103137758>
28: #<Bio::DB::Alignment:0x00000103136ad8>
29: #<Bio::DB::Alignment:0x00000103135f48>
30: #<Bio::DB::Alignment:0x000001031353b8>
31: #<Bio::DB::Alignment:0x00000103134828>
32: #<Bio::DB::Alignment:0x0000010313fb60>
33: #<Bio::DB::Alignment:0x0000010313eee0>
34: #<Bio::DB::Alignment:0x0000010313e260>
35: #<Bio::DB::Alignment:0x0000010313d5e0>
36: #<Bio::DB::Alignment:0x0000010313c960>
 => #<Process::Status: pid 30395 exit 0>
2.1.0 :012 >bam.last_command
 => "/Users/ramirezr/.rvm/gems/ruby-2.1.0/gems/bio-samtools-2.3.2/lib/bio/db/sam/external/samtools view  test/samples/LCI/test.bam 'NC_001988.2:0-200'"
```
That is using a freshly installed gem. Can you print your ```sam``` and the last command? Also, I'm wondering on which OS you are teting. I'm using OS X 10.10, with ruby 2.1.0 using rvm. 
Best, 
Ricardo.

**Comment by MatthewRalston** [comment]
I'm failing to reproduce it right now as well, maybe it was my gemset. Thanks again for your time. Would you mind explaining the difference between "query_unmapped" and "is_mapped"  methods? It seems redundant...

**Comment by homonecloco** [comment]
they are a bit redundant. The decision to have them both is that "query_unmapped" is the name in the documentation, and is_mapped is a more intuitive name.
