### ISSUE TITLE
Error during installation 

### ISSUE THREAD

**Issue by MikhailBazhenov** [helios/bioruby-samtools#74]
Trying to install on Ubuntu 22.04, and get this error. Does anyone know how to fix it?

$ sudo gem install bio-samtools
Building native extensions. This could take a while...
ERROR:  Error installing bio-samtools:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.0.0/gems/bio-samtools-2.6.2/ext
/usr/bin/ruby3.0 mkrf_conf.rb

current directory: /var/lib/gems/3.0.0/gems/bio-samtools-2.6.2/ext
/usr/bin/ruby3.0 -I/usr/lib/ruby/vendor_ruby -rrubygems /usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=/var/lib/gems/3.0.0/extensions/x86_64-linux/3.0.0/bio-samtools-2.6.2 RUBYLIBDIR\=/var/lib/gems/3.0.0/extensions/x86_64-linux/3.0.0/bio-samtools-2.6.2
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - https://github.com/samtools/samtools/releases/download/1.6/samtools-1.6.tar.bz2
/var/lib/gems/3.0.0/gems/bio-samtools-2.6.2/ext/Rakefile:11:in `initialize'
/var/lib/gems/3.0.0/gems/bio-samtools-2.6.2/ext/Rakefile:11:in `open'
/var/lib/gems/3.0.0/gems/bio-samtools-2.6.2/ext/Rakefile:11:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<main>'
Tasks: TOP => default => download
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.0.0/gems/bio-samtools-2.6.2 for inspection.
Results logged to /var/lib/gems/3.0.0/extensions/x86_64-linux/3.0.0/bio-samtools-2.6.2/gem_make.out

**Comment by eylenth** [comment]
I have the same issue.

some more trace output:

```sh
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/bin/ruby -rrubygems /cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/bio-samtools-2.6.2 RUBYLIBDIR\=/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/bio-samtools-2.6.2 --trace
** Invoke default (first_time)
** Invoke download (first_time)
** Execute download
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - https://github.com/samtools/samtools/releases/download/1.6/samtools-1.6.tar.bz2
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/bio-samtools-2.6.2/ext/Rakefile:11:in `initialize'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/bio-samtools-2.6.2/ext/Rakefile:11:in `open'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/bio-samtools-2.6.2/ext/Rakefile:11:in `block in <top (required)>'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/cvmfs/biogrid-software.rnd.seeds.basf.net/tools/eb/x86_64/generic/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<main>'
Tasks: TOP => default => download
```

it seems that bio-samtools is not compatible with rake-13.0.6 which is a pre installed library of Ruby 3.2.2.
